version: '2'
services:
    jhipster3-mysql:
        container_name: jhipster3-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/jHipster3/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipster3
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1
